config/routes.rb
Scaff::Application.routes.draw do
  resources :details

  resources :charges

  resources :posts

end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @charges }
    end
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
    @charge = Charge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @charge }
    end
  end

  # GET /charges/new
  # GET /charges/new.json
  def new
    @charge = Charge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charge }
    end
  end

  # GET /charges/1/edit
  def edit
    @charge = Charge.find(params[:id])
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(params[:charge])

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render json: @charge, status: :created, location: @charge }
      else
        format.html { render action: "new" }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charges/1
  # PUT /charges/1.json
  def update
    @charge = Charge.find(params[:id])

    respond_to do |format|
      if @charge.update_attributes(params[:charge])
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge = Charge.find(params[:id])
    @charge.destroy

    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.json
  def index
    @details = Detail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @details }
    end
  end

  # GET /details/1
  # GET /details/1.json
  def show
    @detail = Detail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/new
  # GET /details/new.json
  def new
    @detail = Detail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/1/edit
  def edit
    @detail = Detail.find(params[:id])
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created, location: @detail }
      else
        format.html { render action: "new" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.json
  def update
    @detail = Detail.find(params[:id])

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :courier_id %><br />
    <%= f.number_field :courier_id %>
  </div>
  <div class="field">
    <%= f.label :from_pin %><br />
    <%= f.text_field :from_pin %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.number_field : %>
  </div>
  <div class="field">
    <%= f.label :to_pin %><br />
    <%= f.number_field :to_pin %>
  </div>
  <div class="field">
    <%= f.label :for_250gms %><br />
    <%= f.text_field :for_250gms %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field : %>
  </div>
  <div class="field">
    <%= f.label :for_500gms %><br />
    <%= f.text_field :for_500gms %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field : %>
  </div>
  <div class="field">
    <%= f.label :for_1kg %><br />
    <%= f.text_field :for_1kg %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field : %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>Listing charges</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Courier</th>
    <th>From pin</th>
    <th></th>
    <th>To pin</th>
    <th>For 250gms</th>
    <th></th>
    <th>For 500gms</th>
    <th></th>
    <th>For 1kg</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @charges.each do |charge| %>
  <tr>
    <td><%= charge.id %></td>
    <td><%= charge.courier_id %></td>
    <td><%= charge.from_pin %></td>
    <td><%= charge. %></td>
    <td><%= charge.to_pin %></td>
    <td><%= charge.for_250gms %></td>
    <td><%= charge. %></td>
    <td><%= charge.for_500gms %></td>
    <td><%= charge. %></td>
    <td><%= charge.for_1kg %></td>
    <td><%= charge. %></td>
    <td><%= link_to 'Show', charge %></td>
    <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
    <td><%= link_to 'Destroy', charge, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @charge.id %>
</p>

<p>
  <b>Courier:</b>
  <%= @charge.courier_id %>
</p>

<p>
  <b>From pin:</b>
  <%= @charge.from_pin %>
</p>

<p>
  <b>:</b>
  <%= @charge. %>
</p>

<p>
  <b>To pin:</b>
  <%= @charge.to_pin %>
</p>

<p>
  <b>For 250gms:</b>
  <%= @charge.for_250gms %>
</p>

<p>
  <b>:</b>
  <%= @charge. %>
</p>

<p>
  <b>For 500gms:</b>
  <%= @charge.for_500gms %>
</p>

<p>
  <b>:</b>
  <%= @charge. %>
</p>

<p>
  <b>For 1kg:</b>
  <%= @charge.for_1kg %>
</p>

<p>
  <b>:</b>
  <%= @charge. %>
</p>


<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :c_id %><br />
    <%= f.number_field :c_id %>
  </div>
  <div class="field">
    <%= f.label :from_pin %><br />
    <%= f.number_field :from_pin %>
  </div>
  <div class="field">
    <%= f.label :to_pin %><br />
    <%= f.number_field :to_pin %>
  </div>
  <div class="field">
    <%= f.label :for_250gms %><br />
    <%= f.text_field :for_250gms %>
  </div>
  <div class="field">
    <%= f.label :for_500gms %><br />
    <%= f.text_field :for_500gms %>
  </div>
  <div class="field">
    <%= f.label :for_1kg %><br />
    <%= f.text_field :for_1kg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <tr>
    <th>Id</th>
    <th>C</th>
    <th>From pin</th>
    <th>To pin</th>
    <th>For 250gms</th>
    <th>For 500gms</th>
    <th>For 1kg</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @details.each do |detail| %>
  <tr>
    <td><%= detail.id %></td>
    <td><%= detail.c_id %></td>
    <td><%= detail.from_pin %></td>
    <td><%= detail.to_pin %></td>
    <td><%= detail.for_250gms %></td>
    <td><%= detail.for_500gms %></td>
    <td><%= detail.for_1kg %></td>
    <td><%= link_to 'Show', detail %></td>
    <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
    <td><%= link_to 'Destroy', detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @detail.id %>
</p>

<p>
  <b>C:</b>
  <%= @detail.c_id %>
</p>

<p>
  <b>From pin:</b>
  <%= @detail.from_pin %>
</p>

<p>
  <b>To pin:</b>
  <%= @detail.to_pin %>
</p>

<p>
  <b>For 250gms:</b>
  <%= @detail.for_250gms %>
</p>

<p>
  <b>For 500gms:</b>
  <%= @detail.for_500gms %>
</p>

<p>
  <b>For 1kg:</b>
  <%= @detail.for_1kg %>
</p>


<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scaff</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :c_id %><br />
    <%= f.number_field :c_id %>
  </div>
  <div class="field">
    <%= f.label :c_name %><br />
    <%= f.text_field :c_name %>
  </div>
  <div class="field">
    <%= f.label :fuel_surcharge %><br />
    <%= f.text_field :fuel_surcharge %>
  </div>
  <div class="field">
    <%= f.label :tax %><br />
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :cod_charge %><br />
    <%= f.text_field :cod_charge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>C</th>
    <th>C name</th>
    <th>Fuel surcharge</th>
    <th>Tax</th>
    <th>Weight</th>
    <th>Cod charge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.c_id %></td>
    <td><%= post.c_name %></td>
    <td><%= post.fuel_surcharge %></td>
    <td><%= post.tax %></td>
    <td><%= post.weight %></td>
    <td><%= post.cod_charge %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>C:</b>
  <%= @post.c_id %>
</p>

<p>
  <b>C name:</b>
  <%= @post.c_name %>
</p>

<p>
  <b>Fuel surcharge:</b>
  <%= @post.fuel_surcharge %>
</p>

<p>
  <b>Tax:</b>
  <%= @post.tax %>
</p>

<p>
  <b>Weight:</b>
  <%= @post.weight %>
</p>

<p>
  <b>Cod charge:</b>
  <%= @post.cod_charge %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>